<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPRUMOSL6042" ignored="0" name="Test" tests="20" failures="4" timestamp="16 дек 2017 19:00:12 GMT" time="0.333" errors="0">
  <testcase name="testMult" time="0.023" classname="com.epam.moscow.module4.test.CalculatorTestMult"/>
  <testcase name="testMult" time="0.004" classname="com.epam.moscow.module4.test.CalculatorTestMult"/>
  <testcase name="testMult" time="0.006" classname="com.epam.moscow.module4.test.CalculatorTestMult">
    <failure type="java.lang.AssertionError" message="expected [-3] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [-3] but found [3]at com.epam.moscow.module4.test.CalculatorTestMult.testMult(CalculatorTestMult.java:18)... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testMult -->
  <testcase name="testMult" time="0.004" classname="com.epam.moscow.module4.test.CalculatorTestMult"/>
  <testcase name="testMultt" time="0.003" classname="com.epam.moscow.module4.test.CalculatorTestMult"/>
  <testcase name="testSub" time="0.004" classname="com.epam.moscow.module4.test.CalculatorTestSub"/>
  <testcase name="testSub" time="0.003" classname="com.epam.moscow.module4.test.CalculatorTestSub"/>
  <testcase name="testSub" time="0.003" classname="com.epam.moscow.module4.test.CalculatorTestSub">
    <failure type="java.lang.AssertionError" message="expected [-4] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [-4] but found [2]at com.epam.moscow.module4.test.CalculatorTestSub.testSub(CalculatorTestSub.java:18)... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testSub -->
  <testcase name="testSub" time="0.003" classname="com.epam.moscow.module4.test.CalculatorTestSub"/>
  <testcase name="testSubb" time="0.004" classname="com.epam.moscow.module4.test.CalculatorTestSub"/>
  <testcase name="testDiv" time="0.0" classname="com.epam.moscow.module4.test.CalculatorTestDiv"/>
  <testcase name="testDiv" time="0.01" classname="com.epam.moscow.module4.test.CalculatorTestDiv"/>
  <testcase name="testDiv" time="0.01" classname="com.epam.moscow.module4.test.CalculatorTestDiv"/>
  <testcase name="testDiv" time="0.0" classname="com.epam.moscow.module4.test.CalculatorTestDiv"/>
  <testcase name="testDivv" time="0.0" classname="com.epam.moscow.module4.test.CalculatorTestDiv">
    <failure type="java.lang.AssertionError" message="expected [2.6] but found [2.5]">
      <![CDATA[java.lang.AssertionError: expected [2.6] but found [2.5]at com.epam.moscow.module4.test.CalculatorTestDiv.testDivv(CalculatorTestDiv.java:25)... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testDivv -->
  <testcase name="testSum" time="0.0" classname="com.epam.moscow.module4.test.CalculatorTestSum"/>
  <testcase name="testSum" time="0.003" classname="com.epam.moscow.module4.test.CalculatorTestSum"/>
  <testcase name="testSum" time="0.003" classname="com.epam.moscow.module4.test.CalculatorTestSum"/>
  <testcase name="testSum" time="0.002" classname="com.epam.moscow.module4.test.CalculatorTestSum"/>
  <testcase name="testSumm" time="0.004" classname="com.epam.moscow.module4.test.CalculatorTestSum">
    <failure type="java.lang.AssertionError" message="expected [4] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [3]at com.epam.moscow.module4.test.CalculatorTestSum.testSumm(CalculatorTestSum.java:30)... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testSumm -->
</testsuite> <!-- Test -->
